In [32]:
import numpy as np
ex = np.array([3,2,5,6,7])
ex

array([3, 2, 5, 6, 7])

In [33]:
ex*2


array([ 6,  4, 10, 12, 14])

In [34]:
matrix = np.array([[4,5,6],[2,6,1]])
matrix*2

array([[ 8, 10, 12],
       [ 4, 12,  2]])

In [35]:
import numpy as np
matrix_4x3 = np.array([[2,4,4],
                       [5,3,6],
                       [7,4,5],
                       [6,3,2]])
print(matrix_4x3)

[[2 4 4]
 [5 3 6]
 [7 4 5]
 [6 3 2]]


In [36]:
print(matrix_4x3*2)

[[ 4  8  8]
 [10  6 12]
 [14  8 10]
 [12  6  4]]


In [2]:
import postgresql.connector

ModuleNotFoundError: No module named 'postgresql'

In [1]:
dbcon = postgresql.connector.connect(
    host = "ep-noisy-lake-a8k78ama-pooler.eastus2.azure.neon.tech",
    user = "abinesh",
    password= "SIT-ML-Playground",
    database = "playground",
    connection_timeout= 60,
    ssl_disabled=False)

NameError: name 'postgresql' is not defined

In [ ]:
#cur = dbcon.cursor()
#cur.execute(select *